name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Upgrade pip and install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install production dependencies
          pip install -r requirements.txt
          # If you use a separate file for development dependencies:
          pip install -r requirements-dev.txt || true

      # Run tests using pytest
      - name: Run tests
        run: |
          pytest

